/**
 * generated by Xtext 2.19.0
 */
package org.example.entities.ui.outline;

import java.util.function.Consumer;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;
import org.example.entities.entities.Attribute;
import org.example.entities.entities.Entity;
import org.example.entities.entities.Model;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
@SuppressWarnings("all")
public class EntitiesOutlineTreeProvider extends DefaultOutlineTreeProvider {
  public boolean _isLeaf(final Attribute a) {
    return true;
  }
  
  public void _createChildren(final DocumentRootNode outlineNode, final Model model) {
    final Consumer<Entity> _function = (Entity entity) -> {
      this.createNode(outlineNode, entity);
    };
    model.getEntities().forEach(_function);
  }
}
