/*
 * generated by Xtext 2.19.0
 */
package org.example.entities.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.example.entities.entities.Model
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.junit.Assert
import org.example.entities.entities.EntityType

@ExtendWith(InjectionExtension)
@InjectWith(EntitiesInjectorProvider)
class EntitiesParsingTest {
	
	@Inject extension ParseHelper<Model>
	
	@Test
	def void loadModel() {
		val model = '''
			entity MyEntity { }
		'''.parse
		Assertions.assertNotNull(model)
		val errors = model.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void testParsing() {
		val model = '''
			entity MyEntity {
				MyEntity attribute;
			}
		'''.parse
		val entity = model.entities.get(0)
		Assert.assertEquals("MyEntity", entity.name)
		val attribute = entity.attributes.get(0)
		Assert.assertEquals("attribute", attribute.name)
		Assert.assertEquals("MyEntity", (attribute.type.elementType as EntityType).entity.name);
	}
}
